### ISSUE TITLE
Issue: Monitor ActiveMQ with the JMX integration

### ISSUE THREAD

**Issue by StacySimmons** [newrelic/docs-website#10054]
ActiveMQ YAML configuration snippet is formatted improperly, causing errors when adding this snippet to the metrics configuration file. I found errors beginning at the top with nesting issues, and further down, I believe multiple beans are incorrectly listed on a single line. 

YAML validator confirms an indentation issues here (and further down) that can be frustrating to troubleshoot.

Example 1.
```
collect:
  - domain: java.lang
  event_type: JVMSampleActiveMQ
  beans:
    - query: type=GarbageCollector,name=*
      attributes:
        - CollectionCount
        - CollectionTime
    -query: type=Memory
```

These beans seem to be on the same line, but I believe they are supposed to be one per line.

Example 2.
`- QueueSubscribers - Queues - slave - StatisticsEnabled - StoreLimit - StorePercentUsage `
