### ISSUE TITLE
OTel collector for Prometheus docs are inaccurate

### ISSUE THREAD

**Issue by thezackm** [newrelic/docs-website#14676]
[docs link here](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/collector-configuration-examples/opentelemetry-collector-prometheus/#install-opentelemetry-collector)

In our install docs, we have step 3 listed as 2 parts:
 * install the collector
 * install the contrib distribution to include the prometheus and otlp receivers

>Install [OpenTelemetry Collector Contrib Distro](https://github.com/open-telemetry/opentelemetry-collector-releases/tree/main/distributions/otelcol-contrib) or other distribution including, at least, the following components:
> * [Prometheus receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver)
> * [OTLP exporter](https://pkg.go.dev/go.opentelemetry.io/collector/exporter/otlpexporter)

This is confusing as the link to the contrib distro doesn't have any installation instructions. Additionally, the vanilla install of the OTel collector has both of these components installed by default so the entire process is unnecessary. 

results from running `./otelcol components`:

```yaml
buildinfo:
    command: otelcol
    description: OpenTelemetry Collector
    version: 0.85.0
receivers:
    - name: otlp
      stability:
        logs: Beta
        metrics: Stable
        traces: Stable
    ...
    - name: prometheus
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    ...
```

---

suggested resolution: remove the instructions to install the contrib distro as unneeded.
