### ISSUE TITLE
[Config] Automate building YAML files for the new IA

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#159]
# Description
The new docs site will use the new information architecture (IA) - pages may live in slightly _different_ locations in the _navigation_.

The first attached screenshot is part the larger [IA diagram in whimsical](https://whimsical.com/8tBfw8Squs35bvTo5acsC6). Each "leaf" in that diagram does not represent a single page, but rather a collection of pages. Rather than manually defining where every individual page must go, we may be able to build tooling to help us automate where each _collection_ of pages goes. This will help us build the `.yml` files that drive the navigation.

_NOTE: Regardless of approach, there will be some manual work to define the rules that drive the automation. That work is tracked in a separate ticket_.

## YAML Format
Each top-level nav (see second screenshot) will have it's own `.yml` configuration file (i.e. `full-stack-observability.yml`) and all of these files will live under a specific `src/nav` directory. The format for those files would looks something like the following:

```yml
- title: APM
  url: /docs/full-stack-observability/apm
  children:
    - title: New Relic APM
      url: /docs/full-stack-observability/apm/new-relic
      children:
        - title: Foo
          url: /docs/full-stack-observability/apm/new-relic/foo
        - title: Bar
          url: /docs/full-stack-observability/apm/new-relic/bar
    - title: APM UI Pages
      url: /docs/full-stack-observability/apm/ui-pages
```

## Acceptance Criteria
* [ ] When a migration is run, pages are added to the appropriate YAML file based on their location in the new IA

## Screenshot(s)
![Screen Shot 2020-10-16 at 5 39 40 PM](https://user-images.githubusercontent.com/1946433/96324534-1df65400-0fd7-11eb-9aa1-f6dd0e6a29b3.png)
![Screen Shot 2020-10-16 at 5 26 33 PM](https://user-images.githubusercontent.com/1946433/96324779-53e80800-0fd8-11eb-8d5c-f9093f3fbf1b.png)
