### ISSUE TITLE
[Auto Index Pages] Create pages for all nav paths

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#2340]
## Description

Now that nav YAML file data is used to populate auto index page content, we want to create index pages for all nav paths. Currently, if a nav path must:
- reflect a file directory in `src/content`
- the file directory must have at least one `.md` or `.mdx` file in it.

## Acceptance criteria

If I added the following to the `accounts.yml` file:

```
title: Clintons Fave Docs
path: /docs/clintons-fave-docs
pages:
  - title: PHP agent attributes
    path: /docs/agents/php-agent/attributes/php-agent-attributes
  - title: Enable or disable attributes
    path: /docs/agents/php-agent/attributes/enable-or-disable-attributes
  - title: Attribute examples
    path: /docs/agents/php-agent/attributes/attribute-examples
```

I would see the `accounts.yml` in the left nav AND the submenu of all nested `pages` from the YAML on the auto index page at `docs.newrelic.com/docs/clintons-fave-docs`

Bonus: The `gatsby-plugin-auto-index-pages` only visits and uses `generateHtml()` only when necessary. Necessary = when a `.mdx` file path exists in the file system but not in any nav YAML.

## Related issues / PRs
Follow on to: https://github.com/newrelic/docs-website/pull/2260
