### ISSUE TITLE
Issue: Language agents and distributed tracing

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/docs-website#4703]
## How can we make our docs better?

The example configuration for Java Agent has an invalid format. I confirmed the following format is working.

```
distributed_tracing:
  enabled: true
infinite_tracing:
  trace_observer:
    host: "YOUR_TRACE_OBSERVER_HOST"
```

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/distributed-tracing/enable-configure/language-agents-enable-distributed-tracing/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 95.0.4638.54
* **Device**: Unknown
