### ISSUE TITLE
[Machine Translation] Create method for excluding specific directories/types

### ISSUE THREAD

**Issue by rudouglas** [newrelic/docs-website#4734]
## Summary
><!> Please use the https://github.com/newrelic/docs-website/tree/feature/machine-translation feature branch

Currently, our process is to only include files with `translate: language` in the frontmatter. The new functionality will now send all files that don't have `translate: language`, but we want to be able to set specific exclusions.

We will need to include logic for excluding certain doc [types](https://docs.newrelic.com/docs/style-guide/processes-procedures/use-content-types-text-formats/) and specific directories and their sub-directories. This should be done via a yaml file that content writers can update easily. Each exclusion list can be an array of entries For example:

```yaml
     excludePath:
         - /docs/release-notes
         - /whats-new
     excludeTypes:
         - landingPage
         - troubleshooting
```

This would exclude those directories and all their sub-directories, as well as any pages with `type` set to `landingPage` or `troubleshooting` from being sent for translation. 

Changes will need to be made to the [add-files-to-translation-queue.js](https://github.com/newrelic/docs-website/blob/feature/docs-upgrades/scripts/actions/add-files-to-translation-queue.js) script which initially marks files for translation.

Separate exclusions may be needed for each Locale Language so this will also need to be taken into account.

```yaml
excludePath:
    jp:
        - /docs/release-notes
        - /whats-new
...
```

## Acceptance Criteria
 - [x] Pages are excluded and not marked for translation, based on contents of a yaml file
 - [x] Write tests for various types of exclusions we might need (type, file paths)
