### ISSUE TITLE
[GitHub Actions] Investigate the benefits of reusable workflows

### ISSUE THREAD

**Issue by rudouglas** [newrelic/docs-website#5078]
## Description

GitHub just GA'ed the ability to create reusable workflows for organizations. 

https://github.blog/2021-11-29-github-actions-reusable-workflows-is-generally-available/

This could allow us to drastically reduce the amount of duplicated code in our workflows, across all repo's. It could mean far fewer workflows to maintain if we have a single source of truth for specific reusable steps.

Some examples of where that would be convenient:

 - Managing PR/Release workflows across repo's, particularly 3rd-Party-Apps that all use the essentially the workflows. To make a change we have to update each one individually, this would allow us to only have to update a single workflow
 - Upgrading the version of Node we use across all workflows via a single workflow
 - Reusable workflows for things like Enabling/Disabling Branch Protection, running tests, PR comments/labels/Project Board routing, Releases etc

### Acceptance Criteria

 - [ ] Investigate the impact this could have on the size of the codebase we maintain
 - [ ] Investigate how easy this would be to implement and any security implications
 - [ ] Follow-up tickets for implementing the changes

**Comment by rudouglas** [comment]
This can be

**Comment by rudouglas** [comment]
## Org Level

<details><summary>Setup Environment</summary>

This would also allow us to control the version of Node we use in a single place, we can update here then roll out the update across each workflow by just changing `devensetuprepo@v1` version number.

```
- name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Cache dependencies
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
```

</details>

 - Implemented in 8 different jobs in Docs
 - 8 jobs in Private Docs
 - 4 jobs in Dev
 - 4 jobs in OSS
 - 3 jobs in BetaDocs
 - 12 jobs in Quickstarts
 - 2 jobs in I/O
 - `Total 41`


#### Linting/Tests:
 - A single workflow reusable in every repo for each

#### Other Examples
 - auto-assign-reviewer
 - auto-comment

## Repo Level

#### Disable/Enable Branch Protection:
 - These would be best placed at a repo level because branch protection is different in each repo. When we change branch protection rules we need to update across individual workflows and this would allow us to just have to change it in a single location
    - E.g. same branch protections duplicated 3 times in Quickstarts

<details><summary>Quickstart Validation</summary>

```
- name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: validation_gate.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Get PR number
        id: get_pr_number
        run: |
          export PR_NUMBER=$(cat artifact/pr_number.txt)
          echo "::set-output name=pr-number::$PR_NUMBER"
```

</details>

 - Used in 9 different jobs in Quickstarts repo

## 3rd Party Apps

There are 5 identical workflows in each app repo, with 27 apps thats `130 Duplicates` that could be reduced
