### ISSUE TITLE
[Localization Workflow] Create a GitHub action that checks for MDX files with `translate` field in frontmatter

### ISSUE THREAD

**Issue by caylahamann** [newrelic/docs-website#531]
## Description 
We need to create a GitHub action that checks MDX files in our content folder for the `translate` field whenever a new PR is merged. It will then save all the slugs to an artifact. 

## AC
* [ ] Job triggered by each PR into `develop` 
* [ ] Saves the slugs for newly updated content with `translate` frontmatter to the artifact

**Comment by zstix** [comment]
We can probably use [`on.push.path`](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths) to only run the action when we've pushed updates to `mdx` files to `main`:

```yml
on:
  push:
    branches:
      - main
    paths:
      - '**.mdx'
```

**Comment by zstix** [comment]
For getting a list of files that changed in a PR, there's a decent solution presented in [this thread](https://github.community/t/get-list-of-files-on-pull-request-merge/17226) that uses `curl` and `jq`:

```yml
steps:
  - name: List files
    id: list-files
    run: |
      URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
      echo "::set-output name=FILES::$(curl -s -X GET -G $URL | jq -r '.[] | .filename')"
```

We could then use `steps.list-files.outputs.FILES` in a following step - perhaps supply the list of files to a node script?

**Comment by zstix** [comment]
> perhaps supply the list of files to a node script?

It looks like we can use step [`with`](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepswith) to set environment variables, which would make accessing them in a node script as trivial as `process.env.FILES`:

```yml
steps:
  # above step(s)...
  - name: Get files to translate
    id: get-files-to-translate
    run: echo"::set-output name=TO_TRANSLATE::$(yarn our-script)"
    with:
      - files: ${{ steps.list-files.outputs.FILES }}
```

And then the _next_ step could save `steps.get-files-to-translate.outputs.TO_TRANSLATE` to an artifact.
