### ISSUE TITLE
[Sustaining] Update github-scripts

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/docs-website#5793]
## Description
The Github action we use to enable/disable branch protection, github-script, is currently on version 5 and we're running version 1.
We have also observed 404 errors coming from v1 in the [instant-observability-website](https://github.com/newrelic/instant-observability-website/runs/4940934308?check_suite_focus=true).

To avoid running into errors let's upgrade our version of github-script.

### helpful links
- [V5 breaking changes](https://github.com/actions/github-script#breaking-changes-in-v5)

#### before
```yaml
      - name: Temporarily disable branch protection
        id: disable-branch-protection
        uses: actions/github-script@v1
        with:
          github-token: ${{ secrets.OPENSOURCE_BOT_TOKEN }}
          previews: luke-cage-preview
          script: |
            const result = await github.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: null,
              restrictions: null,
              enforce_admins: null,
              required_pull_request_reviews: null
            })
            console.log("Result:", result)
```
#### after
```yaml
      - name: Temporarily disable branch protection
        id: disable-branch-protection
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.OPENSOURCE_BOT_TOKEN }}
          previews: luke-cage-preview
          script: |
            const result = await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: null,
              restrictions: null,
              enforce_admins: null,
              required_pull_request_reviews: null
            })
            console.log("Result:", result)
```
Notice that the changes are just updating the version and add `.rest` to the call path.

## AC
- [ ] All instances of github-script have been updated to v5
