### ISSUE TITLE
Issue: Ignore and include Prometheus metrics

### ISSUE THREAD

**Issue by kpiroto** [newrelic/docs-website#6781]
## How can we make our docs better?
It's not clear to me how include / exclude metrics should be configured.

I have the following config.yam file on my nri-prometheus pod, which was deployed using helm nri-bundle chart version `3.4.0`:

```
scrape_enabled_label: newrelic.io/scrape
scrape_endpoints: false
scrape_services: true
transformations:
- description: Cluster Autoscaler
  ignore_metrics:
  - except:
    - cluster_autoscaler_nodes_
    - cluster_autoscaler_unschedulable_pods_
    - cluster_autoscaler_cluster_safe_to_autoscale
    - cluster_autoscaler_evicted_pods_total
    prefixes:
    - cluster_autoscaler_
- description: Coredns Rules
  ignore_metrics:
  - except:
    - coredns_panics_total
    - coredns_dns_responses_total
    - coredns_dns_requests_total
    - coredns_dns_request_duration_seconds_
    prefixes:
    - coredns_
```
Follows the relevant helm values:
```
nri-prometheus:
  config:
    scrape_enabled_label: newrelic.io/scrape
    transformations:
    - description: Cluster Autoscaler
      ignore_metrics:
      - except:
        - cluster_autoscaler_nodes_
        - cluster_autoscaler_unschedulable_pods_
        - cluster_autoscaler_cluster_safe_to_autoscale
        - cluster_autoscaler_evicted_pods_total
        prefixes:
        - cluster_autoscaler_
    - description: Coredns
      ignore_metrics:
      - except:
        - coredns_panics_total
        - coredns_dns_responses_total
        - coredns_dns_requests_total
        - coredns_dns_request_duration_seconds_
        prefixes:
        - coredns_
    verbose: true
  image:
    pullSecrets:
    - name: docker-hub-auth

```

My cluster-autoscaler and coredns services have been annotated with `newrelic.io/scrape = "true"`, and without those filters above, all metrics are ingested.
I have restarted the nri-prometheus pod after the deploy, also.

Could you please help me to understand what am I missing?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/ignore-or-include-prometheus-metrics/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown
